hc-install: support fetching of manually entered image URLs
Previously only a local file path was supported, now anything
supported by fetch(1) should work.

diff --git a/tools/hc-install b/tools/hc-install
--- a/tools/hc-install
+++ b/tools/hc-install
@@ -479,33 +479,49 @@ if [ $? == "1" ]; then
 fi
 image_selected=`cat $tmpfile`	
 if [ $image_selected == "5" ]; then
-        dialog --inputbox "Please enter the path of the FreeBSD image (.xz):\n\
+    dialog --inputbox "Please enter the path of the FreeBSD image (.xz):\n\
 " 10 60 / 2>$tmpfile	
     
     if [ $? == "1" ]; then
         echo cancelled
         exit 1
     fi
-image_selected=`cat $tmpfile`
+    image_selected=`cat $tmpfile`
+    needs_download="maybe"
 fi
 
 if [ $image_selected == "1" ]; then
     image_selected="/cdrom/9.1-STABLE-amd64.tar.xz"
+    needs_download="no"
 fi
 if [ $image_selected == "2" ]; then
     image_selected="/nfs/mfsbsd/8.2-amd64-zfs.tar.xz"
+    needs_download="no"
 fi
 if [ $image_selected == "3" ]; then
-    # In case we're in the OVH rescue-pro environment, which has no free space.
-    mkdir $tmp_dir; mount_mfs -o rw -s 384M md $tmp_dir
-    fetch -o $tmp_dir/$latest_image ftp://ftp.hybrid-cluster.com/$latest_image
-    image_selected="$tmp_dir/$latest_image"
+    image_selected="ftp://ftp.hybrid-cluster.com/$latest_image"
 fi
 if [ $image_selected == "4" ]; then
+    image_selected="http://ftp.hybrid-cluster.com/$latest_image"
+fi
+
+if [ "$needs_download" = "maybe" ] ; then
+    [ -r "$image_selected" ] && needs_download="no"
+fi
+if [ "$needs_download" = "yes" ] ; then
     # In case we're in the OVH rescue-pro environment, which has no free space.
-    mkdir $tmp_dir; mount_mfs -o rw -s 384M md $tmp_dir
-    fetch -o $tmp_dir/$latest_image http://ftp.hybrid-cluster.com/$latest_image
-    image_selected="$tmp_dir/$latest_image"
+    mkdir -p $tmp_dir && mount_mfs -o rw -s 384M md $tmp_dir
+    fetch -o $tmp_dir/image.tar.xz "$image_selected"
+    if [ $? -ne 0 ] ; then
+        echo "Download of $image_selected to $tmp_dir/image.tar.xz failed" 1>&2
+        exit 1
+    fi
+    image_selected="$tmp_dir/image.tar.xz"
+fi
+
+if [ ! -r "$image_selected" ] ; then
+    echo "File $image_selected can not be read" 1>&2
+    exit 1
 fi
 
 # Installation mit UFS 
