Write out the bootcode after extracting it.

diff --git a/tools/zfsinstall b/tools/zfsinstall
--- a/tools/zfsinstall
+++ b/tools/zfsinstall
@@ -223,12 +223,6 @@ for DEV in ${DEVS}; do
 	fi
 	echo " done"
 
-	echo -n "Configuring ZFS bootcode on ${DEV} ..."
-		if ! /sbin/gpart bootcode -b ${MNT}/boot/pmbr -p ${MNT}/boot/gptzfsboot -i 1 ${DEV} > /dev/null; then
-		echo " error"
-		exit 1
-	fi
-	echo " done"
 	/sbin/gpart show ${DEV}
 done
 
@@ -330,6 +324,13 @@ else
 		echo " error"
 		exit 1
 	fi
+fi
+echo " done"
+
+echo -n "Configuring ZFS bootcode on ${DEV} ..."
+    if ! /sbin/gpart bootcode -b ${MNT}/boot/pmbr -p ${MNT}/boot/gptzfsboot -i 1 ${DEV} > /dev/null; then
+    echo " error"
+    exit 1
 fi
 echo " done"
 
